### PR TITLE
Update the website

### PR DESCRIPTION
**Pull request by waveform80**
From an entirely tastefully named branch...

### CODE REVIEW

**Comment by waveform80** [comment]
Pre-release versions are broken when selecting install instructions and I said something about making the issue search more specific? (or something like that?)

**Comment by waveform80** [comment]
@bennuttall Don't merge this yet; if we're going to do a full rebuild on the website anyway I'd like a chance to do the db mods we talked about the other evening (moving build logs onto the web-side)

**Comment by bennuttall** [comment]
Ok

**Comment by waveform80** [comment]
Nearly there; this push fixes the project page generation, cleans up all the redundant functions, and gets the tests back to a working state (at least on one python ver anyway; will see what CI thinks about the rest).

Now to get the logs actually written to the fs, and out of the db with a new scribe message...

**Pull request merged**
