### PR TITLE
Update deploy_slave.sh

### PR DESCRIPTION
**Pull request by jgillis**
Adding Ipopt: a mature open-source nonlinear constrained optimizer ( https://coin-or.github.io/Ipopt/ )
A lot of _smart_ autonomous decision making can be formulated as constrained optimization (e.g. model predictive control of a building heater), which is an attractive use-case for a low-cost embedded system like Raspberry Pi.
Needed for  the casadi package, but others might benefit too (ipopt, pyipopt)

### CODE REVIEW

**Comment by bennuttall** [comment]
It looks like [casadi](https://pypi.org/project/casadi/#files) and [pyipopt](https://pypi.org/project/pyipopt/#files) don't release source packages anyway.

If installing this package makes [ipopt](https://www.piwheels.org/project/ipopt/) build successfully, it might be worth it. I'll try it when I get chance.

**Comment by jgillis** [comment]
I'm the maintainer of the former, I had a first succesful build on piwheels yesterday in fact with a now pulled source package; will check the ipopt package for you..

**Comment by jgillis** [comment]
fwiw, ipopt package seems to install fine with the added dependency, though it does also need the Cython python package

**Comment by AliRasoulzadeh1990** [comment]
> Adding Ipopt: a mature open-source nonlinear constrained optimizer ( https://coin-or.github.io/Ipopt/ ) A lot of _smart_ autonomous decision making can be formulated as constrained optimization (e.g. model predictive control of a building heater), which is an attractive use-case for a low-cost embedded system like Raspberry Pi. Needed for the casadi package, but others might benefit too (ipopt, pyipopt)

After installing IPOPT this way, can I pip install CasADi and will it work with IPOPT? Or it needs another installation method?

**Pull request merged**
